-- SQL скрипт для оптимизации базы данных Firebird
-- Рекомендации по созданию индексов для улучшения производительности поиска материалов

-- 1. Индексы для таблицы ORDERS
-- Основные индексы для фильтрации заказов
CREATE INDEX IDX_ORDERS_DATECREATED ON ORDERS (DATECREATED DESC);
CREATE INDEX IDX_ORDERS_ORDERSTATUS ON ORDERS (ORDERSTATUS);
CREATE INDEX IDX_ORDERS_DELETED ON ORDERS (DELETED);
CREATE INDEX IDX_ORDERS_ORDERNO ON ORDERS (ORDERNO);

-- Составной индекс для основных фильтров
CREATE INDEX IDX_ORDERS_MAIN_FILTERS ON ORDERS (DELETED, ORDERSTATUS, DATECREATED DESC);

-- 2. Индексы для таблицы ORDERITEMS
CREATE INDEX IDX_ORDERITEMS_ORDERID ON ORDERITEMS (ORDERID);
CREATE INDEX IDX_ORDERITEMS_ORDERITEMSID ON ORDERITEMS (ORDERITEMSID);

-- 3. Индексы для таблицы ITEMSDETAIL
CREATE INDEX IDX_ITEMSDETAIL_ORDERITEMSID ON ITEMSDETAIL (ORDERITEMSID);
CREATE INDEX IDX_ITEMSDETAIL_MODELNO ON ITEMSDETAIL (MODELNO);
CREATE INDEX IDX_ITEMSDETAIL_GOODSID ON ITEMSDETAIL (GOODSID);

-- Составной индекс для связи с моделями
CREATE INDEX IDX_ITEMSDETAIL_MODEL_ORDER ON ITEMSDETAIL (MODELNO, ORDERITEMSID);

-- 4. Индексы для таблицы STUFFS (материалы)
CREATE INDEX IDX_STUFFS_STUFFTYPEID ON STUFFS (STUFFTYPEID);
CREATE INDEX IDX_STUFFS_NAME ON STUFFS (NAME);
CREATE INDEX IDX_STUFFS_MARKING ON STUFFS (MARKING);
CREATE INDEX IDX_STUFFS_RECALCGROUPID ON STUFFS (RECALCGROUPID);

-- Составной индекс для поиска по материалам
CREATE INDEX IDX_STUFFS_SEARCH ON STUFFS (STUFFTYPEID, NAME, MARKING);

-- 5. Индексы для таблицы STUFFTYPES
CREATE INDEX IDX_STUFFTYPES_CODE ON STUFFTYPES (CODE);
CREATE INDEX IDX_STUFFTYPES_ID ON STUFFTYPES (ID);

-- 6. Индексы для таблицы MODELS
CREATE INDEX IDX_MODELS_ORDERITEMSID ON MODELS (ORDERITEMSID);
CREATE INDEX IDX_MODELS_MODELNO ON MODELS (MODELNO);

-- 7. Индексы для таблицы MEASURE
CREATE INDEX IDX_MEASURE_MEASUREID ON MEASURE (MEASUREID);
CREATE INDEX IDX_MEASURE_GRMEASUREID ON MEASURE (GRMEASUREID);

-- 8. Индексы для таблицы COLORS
CREATE INDEX IDX_COLORS_COLORID ON COLORS (COLORID);

-- 9. Индексы для таблицы MODELPARTS
CREATE INDEX IDX_MODELPARTS_MODELPARTID ON MODELPARTS (MODELPARTID);
CREATE INDEX IDX_MODELPARTS_MODELID ON MODELPARTS (MODELID);

-- 10. Индексы для таблицы MODELFILLINGS
CREATE INDEX IDX_MODELFILLINGS_MODELPARTID ON MODELFILLINGS (MODELPARTID);

-- 11. Индексы для таблицы RECALCGROUP
CREATE INDEX IDX_RECALCGROUP_RECALCGROUPID ON RECALCGROUP (RECALCGROUPID);
CREATE INDEX IDX_RECALCGROUP_NAME ON RECALCGROUP (NAME);

-- Дополнительные оптимизированные индексы для частых запросов

-- Составной индекс для основного запроса поиска материалов
CREATE INDEX IDX_MAIN_SEARCH_QUERY ON ITEMSDETAIL (GOODSID, MODELNO, ORDERITEMSID);

-- Индекс для быстрого подсчета статистики
CREATE INDEX IDX_STATISTICS_COUNT ON ORDERS (DELETED, ORDERSTATUS, DATECREATED, ORDERID);

-- Индекс для поиска по артикулу материала
CREATE INDEX IDX_STUFFS_MARKING_SEARCH ON STUFFS (MARKING, STUFFTYPEID);

-- Индекс для поиска по названию материала
CREATE INDEX IDX_STUFFS_NAME_SEARCH ON STUFFS (NAME, STUFFTYPEID);

-- Составной индекс для фильтрации по типу материала и дате
CREATE INDEX IDX_ORDERS_DATE_TYPE ON ORDERS (DATECREATED DESC, ORDERSTATUS, DELETED);

-- Статистика для оптимизатора запросов
-- Выполнить после создания индексов для обновления статистики
-- EXECUTE PROCEDURE RDB$STATISTICS;

-- Рекомендации по настройке Firebird:
-- 1. Увеличить размер буферного кэша: DefaultDbCachePages = 10000
-- 2. Настроить размер страницы: DefaultPageSize = 8192
-- 3. Включить мониторинг производительности
-- 4. Регулярно обновлять статистику: gstat -h

-- Примеры запросов для проверки производительности:

-- Проверка использования индексов
-- SET PLAN ON;
-- SELECT * FROM ORDERS WHERE DATECREATED >= '2024-01-01' AND ORDERSTATUS = 3;

-- Анализ плана выполнения
-- SET PLAN ON;
-- SELECT o.ORDERNO, g.NAME, g.MARKING 
-- FROM ORDERS o
-- JOIN ORDERITEMS oi ON o.ORDERID = oi.ORDERID
-- JOIN ITEMSDETAIL itd ON itd.ORDERITEMSID = oi.ORDERITEMSID
-- JOIN STUFFS g ON g.ID = itd.GOODSID
-- WHERE o.DELETED = 0 AND g.NAME CONTAINING 'стекло';

-- Мониторинг производительности
-- SELECT * FROM MON$STATEMENTS WHERE MON$SQL_TEXT CONTAINING 'SELECT';